api = "0.2"

[buildpack]
  id = "paketo-community/ruby"
  name = "Ruby Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/mri"
    sha256 = "cf0ed0f25e924633807e0197197a8cdfd328755fef358950542d327dbf11a301"
    source = "https://github.com/paketo-community/mri/archive/v0.0.101.tar.gz"
    source_sha256 = "e668eec8309c7ba009db52083f2f203ee2a0f9b07a2c403d78403f3541912e46"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/mri/releases/download/v0.0.101/mri-v0.0.101.tgz"
    version = "0.0.101"

  [[metadata.dependencies]]
    id = "paketo-community/bundler"
    sha256 = "b34ed801dd95481fa80826376dc1bad560b8d47e3b431da57b40bba22084906d"
    source = "https://github.com/paketo-community/bundler/archive/v0.0.94.tar.gz"
    source_sha256 = "4d5aea8145752f47764ee111326b9caa2cc3a8fecce1c2f2225134a517929fac"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/bundler/releases/download/v0.0.94/bundler-v0.0.94.tgz"
    version = "0.0.94"

  [[metadata.dependencies]]
    id = "paketo-community/bundle-install"
    sha256 = "c3a4175bf03a5dfba38878d36d0ce97ad72967ab31ac4615fab6eb7fa52cc9e5"
    source = "https://github.com/paketo-community/bundle-install/archive/v0.0.1.tar.gz"
    source_sha256 = "b65496cfb7329aff50df81ca4b0deea290ca116d2b1fd01b9e83b87be7017a22"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/bundle-install/releases/download/v0.0.1/bundle-install-v0.0.1.tgz"
    version = "0.0.1"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.101"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.94"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.1"
